name: Gerar Cobrinha de Contribuições

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Gerar Snake
        uses: Platane/snk@v3
        with:
          github_user_name: yasminvasconceloss
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
